apiVersion: v1
kind: Pod
metadata:
  name: "extract-{{.Index}}"
  labels:
    app: ubuntu-app
spec:
  containers:
  - name: tmbdev-extract
    image: tmbdev/o4extract
    command:
      - /bin/bash
      - -c
      - |
        extract-lines.sh gs://nvdata-ocropus-tess/{{.Item}} gs://nvdata-ocropus-lines/{{.Item}}
    resources:
      requests:
        cpu: 2
        memory: 4G
      limits:
        cpu: 2
        memory: 4G
  restartPolicy: Never
