data:
  nepoch: 20000
  train_bs: 6
  train_shards:
    prefix: pipe:curl -s -L http://storage.googleapis.com/
    buckets: nvdata-ocropus-words
    datasets:
      - shards: uw3-word-0000{00..21}.tar
        choose: 10
      - shards: ia1-{000000..000033}.tar
        choose: 10
      - shards: gsub-{000000..000167}.tar
        choose: 2
      - shards: cdipsub-{000000..000092}.tar
        choose: 2
  val_bs: 12
  val_shards: pipe:curl -s -L http://storage.googleapis.com/nvdata-ocropus-words/uw3-word-0000{22..22}.tar
  num_workers: 8
  augment: distort
model:
  display_freq: 1000
  halflife: 10
  lr: 0.03
  mname: ctext_model_211124
checkpoint:
  every_n_epochs: 5
trainer:
  gpus: 1
  default_root_dir: ./_logs
  max_epochs: 10000
  progress_bar_refresh_rate: 2
