data:
  nepoch: 200000
  train_bs: 4
  train_shards:
    prefix: pipe:curl -s -L http://storage.googleapis.com/
    buckets: nvdata-ocropus-words
    datasets:
      - shards: uw3-word-0000{00..21}.tar  # 20000 samples/shards
        choose: 5
      - shards: ia1-{000000..000033}.tar  # 110000 samples/shard
        choose: 1
      - shards: gsub-{000000..000167}.tar  # 50000 samples/shard
        choose: 2
      - shards: cdipsub-{000000..000092}.tar  # 33000 samples/shard
        choose: 10
      - shards: generated-{000000..000313}.tar  # 10000 samples/shard
        choose: 50
  val_bs: 12
  val_shards: pipe:curl -s -L http://storage.googleapis.com/nvdata-ocropus-words/uw3-word-0000{22..22}.tar
  num_workers: 4
  augment: distort
lightning:
  display_freq: 1000
  lr_halflife: 1
  lr: 0.03
  mname: ctext_model_211124
  textmodel:
    charset_size: 128
  basemodel:
    noutput: 128
checkpoint:
  every_n_epochs: 1
trainer:
  gpus: 1
  default_root_dir: ./_logs
  max_epochs: 10000
  progress_bar_refresh_rate: 2
