data:
  nepoch: 20000
  train_bs: 12
  train_shards: pipe:curl -s -L http://storage.googleapis.com/nvdata-ocropus-words/uw3-word-0000{00..21}.tar
  val_bs: 24
  val_shards: pipe:curl -s -L http://storage.googleapis.com/nvdata-ocropus-words/uw3-word-0000{22..22}.tar
  cache_size: 400e9
  cache_dir: ./_cache
logging:
  wandb:
    log_model: all
    project: ocrorec2
model:
  display_freq: 1000
  halflife: 80
  lr: 0.03
  mname: ctext_model_211120
checkpoint:
  every_n_epochs: 10
trainer:
  default_root_dir: ./_logs
  gpus: 1
  max_epochs: 10000
  progress_bar_refresh_rate: 2
