[tool.vulture]
ignore_decorators = ["@app.command", "@useopt", "@public", "@unused", "@model", "@junk"]
ignore_names = ["make_*", "check_*"]
paths = ["ocropus"]
exclude = ["ocropus/.ipynb_checkpoints/"]
